Implement arenas spatial (#174)
* added 2011 census data to data/raw, updated readme

* add geopandas to environment

* working prototype, must be split into communities and arrondissements

* save changes

* installed dependency `pyarrow` to store matrix as feather (.ft)

* Remove .csv with initial population and recurrent mobility matrix

* decided to use pickle format for initN and recurrent mobility matrix

* modified COVID19_SEIRD_sto so it would work again

* modified COVID19_SEIRD so it would work again

* notebook for census data extraction

* renamed `parameters.py` --> `model_parameters.py`

* added loading of rec. mobility mtx to parameter loading function

also general tweaks to the function, update of docstring etc

* Updated all docstring documentation in models.py, checked for uniformity

* split initN and rec. mobility mtx according to arrondissements or munici

* removed testing parameters in deterministic model for uniformity

* removed twallema-discrete-time-stochastic-model notebook, obsolete

* renamed model notebook

* add NIS codes as custom coordinates for spatial axis

* extract names from census excel

* NIS codes indices of pickles are int64 instead of strings

* added names to initN

* save output initN and rec. mobility matrix to pickle format

* change initN pickle directory in models.py

* added index title to initN dataframe

* add function to covert name into NIS code

* changed path of rec. mobility mtx in models.py

* gave index a name in initN_df

* finished extraction of census data, removed all output before gitting

* Incorporate averaging of multiple binomial draws into model

* verified deterministic and stochastic model are still working

* changed to hardcoded NIS codes to avoid relative path errors

not elegant and must be fixed

* Optimized the way custom coordinates are handled

* verified demo notebook is working

* removed output from `twallema-spatial-stochastic.ipynb`

* moved data extraction outside scratch folder

* update data readme

* update model docs

* more changes to model documentation

* typos in models.md

* renamed data/raw/geological --> data/raw/geopandas/BE

it's not GIS technically speaking

* adjusted directory in notebook 0.1-twallema-spatial-stochastic

* use dates in checkpoints and simulations

* maps are saved to new folder notebooks/results

* save census data as csv rather than pickles

* remove output from twallema-extract-census-data

* verify everything works in twallema-spatial-stochastic

* renamed 'NIS' --> 'place'

* clear notebook output

* output maps to results folder

* added function to models/utils.py to read list of NIS  coordinates

* renamed NIS --> place in models.md

not very elegant in math mode do

* Add personal notebooks for exploration

* Explorations and running notebooks (no significant changes)

* Add sketches that will be removed later

* Upload new mobility CSVs, add more age-stratification

model_parameters.py: rather than taking the final value `[-1]` of `dICU_R` e.a., take the full age-stratified values, if `age_stratification==True`

models.py: add newly stratified parameters to parameters_stratifed_names

Add commentary to Notebooks

* Make age stratification more correct

Add dens_dep function for use with Arenas spatial extension

change NA parameter values with zeros in age-stratified parameters

Change order of parameters in the definition of `integrate` in order to avoid `validate` error.

Minor changes in Notebook

* Add post-2011 geography, and change load-in in Notebook

* Update NIS_name with post-2019 convention

Taken from spatial COVID GitHub

* Minor Notebook change

* Minor comments and Notebook executions

* Add NIS-area dictionary CSV

* Add absolute path and `name` argument to read_csv in `read_coordinates_nis(name)`

And some minor Notebook changes

* Minor structural changes (see description) and add area CSV

Add area per NIS (municip, arrond, province)
Add `utils.py` functions `read_areas` and `read_pops` (probably deleted later)
Remove copy of `models.py` function `COVID_SEIRD_sto_spatial` (was doubly defined)
Remove square brackets around `self_stratification` in `base.py` validation function

Minor Notebook changes (probably changed later)

* Add methods to load spatial data

Update `area_arrond.csv` and other aggregations to better format.

Add methods to load spatial data (`area`, `pi`, `sg`) in `model_parameters.py`
Add option to load spatially stratified `initN` in `polymod.py`
Modify functions to load areas in `utils.py` (probably deleted later)

MInor changes in scratch Notebook

* Add changes to `base.py` that Joris VdB suggested

See https://github.com/UGentBiomath/COVID19-Model/pull/161/files#diff-67ef6c0b81f7e0845d52d9a7c9f40bedR90-R95

Other changes are minor

* Implement full Arenas probability

`models.py`: add effective populations and effective infection probabilities. Note: these now go up to 9 percent of infection probability, which is unrealistically high.
`model_parameters.py`:  Little syntax corrections to `area`, and add age-stratification to the days in certain hospital stages (this must have been kept out for a reason, though!)

Scratches in Notebook

* Update Belgian mobility and areas on prov/arrond/municip level

* Change recurrent mobility source to post-2019 data

... and minor scratches in Notebook

* Implement spatial stratification per arr, prov or mun

Add spatial argument to `polymod.get_interaction_matrices` and `get_COVID19_SEIRD_parameters`
```
spatial == 'mun' / 'arr' / 'prov'

Changes names of data in `data/interim/demographic` to facilitate a smooth CSV read-out.
```

* Add Brussels-Capital to province data

And minor changes in the function description of `polymod`, `model_parameters` and `utils`

Scratches in Notebook

* Adjust read_coordinates_nis() to the conventions

* Explicit (non-pythonic) definition of effective populations and probabilities

And minor changes (correct errors).
Scratches in Notebook

* Ignore last initN column; include timestep parameter; rephrase probabilities

And again, minor scratches in Notebook

* Revert changes in age-stratification (due to nan's), correct mistakes in models.py

And scratches in Notebook

* Fix bug: parameter h was used twice (and change hardcoding 'arr' to 'prov')

And scratches in notebook

* Notebook scratches

* Add spatial parameter in `get_interaction_matrices`; load spatial initN data

* Add raw data on population structure from Statbel. Update README

* Replace `initN` files with latest StatBel data

* Add method to make geopandas maps out of simulation results

* Correct error in probabilty (error also fixed in presentation)

* Include spatial test scenario (spatial='test') for the three main arrondissements

And update readme + minor changes in Notebooks + include new CSV files for easy implementation in the existing code.

* Create new clean Notebook, and fix possibility of age_stratified=None

* Create geopandas plotting environment in new Notebook

* function to draw and assign MCMC samples to model, function to perform MC sims

* changes to notebook

* Add some changes for proper merging with spatial model and twallema's PR137

* Changes to the plotting environment (using Tijs' MC_sim results)

* Minor changes for plotting of example jpegs

* fix assignment of prevention parameter

* integrate MC_sim into sim of `base.py`

* remove MC_sim for utils.py

* changes to notebook

* clear output of notebook

* Change in hardcode (to be fixed later)

And nonsubstantial changes in notebook

* Scratches

* Create function `show_map` in `visualization` for spatial simulation

Plot a snapshot of the median evolution of the infection on a Geopandas map, with the possiblity of also showing time series on the side.

Handy tool for quick visualisation of the results of spatial simulations.

* Add social_policy_func function to utils

* Add verbose option to base

* Change legend information to show_maps function

* Quick bug fix in social_policy_func

* Fix bug in show_map function

* Fix error in index of effective population per age per patch

* Make legend entry for uncertainty more compact

* Clean up Notebook using newly defined functions and more structure

* Create show_graphs function

* Minor changes to Notebook (increased structure)

* Add zarr package to environment and setup for saving model outputs

Make sure this is done in the correct way

* Delete mistyped line

* Change attributes to regular dict ("up one level")

Necessary for saving output as zarr file

* Add function open_sim to open simulation output from the database

* Add extra print line to verbose output in read_sim()

* Update README with new section "simulated"

Used to save simulated data

* Add simulated data from 100 spatial simulations in data/simulated

* Add simulated data from provincial and national simulations to data/simulated

* Update notebook working environment for easy use

Currently the show_maps and show_graphs functions do not function because of an error related to the `quantile` function of xarray:
``
ValueError: dimension 'draws' on 0th function argument to apply_ufunc with dask='parallelized' consists of multiple chunks, but is also a core dimension. To fix, rechunk into a single dask array chunk along this dimension, i.e., ``.chunk({'draws': -1})``, but beware that this may significantly increase memory usage.
``

* Add argument `spatial` in model init with default None for naming coordinates

Including validation. Currently works by calling the coordinate 'place' (but there must be a nicer way to implement this).

* Change hardcoded NIS-coordinates to automatically interpreted NIS-list

The trigger for automatically interpreting coordinates is 'place' (this triggers the function read_coordinates_nis with the correct spatial stratification.

* Prevent Exception when `coordinates == None`

* Clean up and restart Notebook

* Check off some items on to-do list

* Create new Notebook for exploring calibration in spatial context

* Correct typo

* Update location of `get_interaction_matrices` function

* Add comments to exploratory calibration notebook

* Fix typo in function description

* Add additional notes (no code)

* Undo commit "Change attributes to regular dict ('up one level')"

Commit 77b22e9746efe458d4d46e6e83605122ad229148

* Add/modify verbose option in simulation

Especially useful for long simulations (for spatial)

* Update save and open such for handling parameter dictionary

* Convert disk array to numpy array in open_sim

Disk array cannot be read by graphing and mapping functions

* Delete description upon opening saved simulation results

* Update function description of open_sim

* Add comments

* Minor changes to notebook

Co-authored-by: twallema <tijs.alleman@ugent.be>
Co-authored-by: Michiel Rollier <Michiel.Rollier@UGent.be>